#App

log_directory: ./logs

#Flask
MAX_CONTENT_SIZE: 10000000000

#JWT
JWT_TOKEN_LOCATION: 
  - headers
  - query_string

JWT_HEADER_TYPE: JWT
JWT_COOKIE_SECURE: True
JWT_COOKIE_CSRF_PROTECT: False
JWT_SECRET_KEY: null
JWT_IDENTITY_CLAIM: sub

JWT_VERIFY_EXPIRATION: True
JWT_ACCESS_TOKEN_EXPIRES : 360000
JWT_REFRESH_TOKEN_EXPIRES : 10000

#AWS
## default 
AWS_ACCESS_KEY_ID: null
AWS_SECRET_ACCESS_KEY: null
AWS_DEFAULT_REGION: us-east-1

## cognito
pool_name: atx-cloud
AWS_COGNITO_DOMAIN: null
AWS_COGNITO_USER_POOL_ID: us-east-1_yZkSjc3os
AWS_COGNITO_USER_POOL_CLIENT_ID: null
AWS_COGNITO_USER_POOL_CLIENT_SECRET: null

## S3
bucket_name: atx-cloud-dev

## MongoDB
MONGO_HOST: mongo ## in production should it be 'mongo' in container
MONGO_PORT: 27017
MONGO_DBNAME: atx-cloud-test
MONGO_INITDB_ROOT_USERNAME: root
MONGO_INITDB_ROOT_PASSWORD: null

## RabbitMQ
RABBITMQ_HOST: rabbitmq
RABBITMQ_PORT: 5672
RABBITMQ_USERNAME: root
RABBITMQ_PASSWORD: null

## REDIS

REDIS_HOST: redis
REDIS_PORT: 6379
REDIS_PASSWORD: null

## temporary directory to store files
TEMP_DIRECTORY: temp

### Table information

DATA_TABLES:
  application_data:
    table_name: application_data
    description: application data (single document)
    key: id
    indexes:
      - id 
  user_configs:
    table_name: user_configs
    description: user settings 
    key: username
    indexes:
      - username
  metadata.wafers:
    table_name: metadata.wafer_informations
    description: wafer information
    key: wafer_id
    indexes:
      - wafer_id 
  metadata.chips:
    table_name: metadata.chip_informations
    description: chip information
    key: chip_id
    indexes:
      - chip_id
  metadata.dbits:
    table_name: metadata.dbit_runs
    description: DBit Run data (post processed)
    key: run_id 
    indexes:
      - run_id
  studies.qc:
    table_name: studies.qc
    description: Study file information 
    key: id
    indexes:
      - id



