#JWT
JWT_TOKEN_LOCATION: 
  - headers
  - query_string
JWT_HEADER_TYPE: JWT
JWT_COOKIE_SECURE: True
JWT_COOKIE_CSRF_PROTECT: False
JWT_ALGORITHM: RS256
JWT_SECRET_KEY: wosqwiepuqwrepvb3p9v297923972379239
JWT_IDENTITY_CLAIM: sub

JWT_VERIFY_EXPIRATION: True
JWT_ACCESS_TOKEN_EXPIRES : 100000
JWT_REFRESH_TOKEN_EXPIRES : 100000

#AWS
## default 
AWS_ACCESS_KEY_ID: null
AWS_SECRET_ACCESS_KEY: null
AWS_DEFAULT_REGION: null

## cognito
pool_name: null
AWS_COGNITO_DOMAIN: null
AWS_COGNITO_USER_POOL_ID: null
AWS_COGNITO_USER_POOL_CLIENT_ID: null
AWS_COGNITO_USER_POOL_CLIENT_SECRET: null

## S3
bucket_name: null
