
version: "3.7"

volumes:
  workingdir: 
    driver: local

services:
  atx-cloud:
    container_name: atx-cloud
    working_dir: $HOME/work/AtlasWebService
    # network_mode : host
    image: atx-cloud
    build: . 
    user: 502:20
    ipc: host
    ports:
      - 5000:5000
    #restart: always
    depends_on:
      - mongo
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers:/stc/sudoers:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro 
      - $HOME:$HOME
    environment:
      - DISPLAY=$DISPLAY
      - TZ=America/New_York
    command: uwsgi --http 0.0.0.0:5000 --module main:app

  atx-cloud-test:
    container_name: atx-cloud-test
    working_dir: $HOME/work/AtlasWebService
    # network_mode : host
    image: atx-cloud
    build: . 
    user: 502:20
    ipc: host
    ports:
      - 5001:5000
    #restart: always
    depends_on:
      - mongo
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers:/stc/sudoers:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro 
      - $HOME:$HOME
    environment:
      - DISPLAY=$DISPLAY
      - TZ=America/New_York
    #command: uwsgi --http 0.0.0.0:4001 --module main:app
    command: python3 /$HOME/work/AtlasWebService/main.py

  mongo:
    image: mongo:4
    hostname: mongo 
    container_name : mongo
    user: 502:20
    restart: always
    ipc: host
    # network_mode: host ## localhost is enough
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=atx!cloud!scalphunter
      - DISPLAY=$DISPLAY
      - TZ=America/New_York
    volumes:
      - $HOME/work/mongodb/data/db:/data/db

